[project]
name = "rachu-ciach"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "db-sqlite3>=0.0.1",
    "sqlalchemy>=2.0.44",
]
